name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
        
    - name: Install dependencies
      run: |
        cd web
        npm ci
        
    - name: Build
      run: |
        cd web
        npm run build
        
    - name: Copy public assets to dist
      run: |
        cp web/public/cleanup.js dist/
        cp web/public/.nojekyll dist/
        
    - name: Add cache busting metadata
      run: |
        echo "Cache-Control: no-cache, no-store, must-revalidate" > dist/_headers
        echo "Pragma: no-cache" >> dist/_headers
        echo "Expires: 0" >> dist/_headers
        echo "/* /index.html 200" > dist/_redirects
        echo "Build timestamp: $(date)" > dist/version.txt
        echo "Version: 5.0.0" >> dist/version.txt
        ls -la dist/ | head -20
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
        cname: false