name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd web
        npm ci
        
    - name: Build
      run: |
        cd web
        npm run build
        
    - name: Verify build output
      run: |
        echo "=== Listing dist directory ==="
        ls -la dist/
        echo "=== Checking index.html ==="
        head -15 dist/index.html
        echo "=== Checking cleanup.js ==="
        ls -la dist/cleanup.js
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
        enable_jekyll: false
